version: '3.1'

services:
  cms-db: 
    image: "postgres:14"
    container_name: "cms-db"
    environment:
      - POSTGRES_DB=cmsdb
      - POSTGRES_USER=cmsuser
      - POSTGRES_PASSWORD=example
  cms-db-init:
    image: "tico88612/cms-db-init:latest"
    container_name: "cms-db-init"
    depends_on:
      - cms-db
    env_file: 
      - ".env"
      - "config/config.env"
